name: Build and publish www artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build -- --prod
      - uses: actions/upload-artifact@v4
        with:
          name: daily-www
          path: www
          retention-days: 7
